### PR TITLE
Unignore and fix `integration-tests::spog::spog_dependencies`, refactor `integration-tests`

### PR DESCRIPTION
**Pull request by i386x**
Unignore and fix `integration-tests::spog::spog_dependencies` by updating expected values from responses.

### CODE REVIEW

**Comment by i386x** [comment]
I have this on my machine:
```
[2024-06-11T13:55:15Z INFO  spog] [
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/service-telemetry-rhel8-operator@sha256:5918c535344b0d0165fe2cd5e4afafbffcf14f09a2759675c765691917fb1459?tag=1.5.1-3"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/prometheus-webhook-snmp@sha256:fc60b27cb8b8806a71dc0faf7de41be39082d5a9a8c92ca0583e6339471a7513?tag=1.5.2-3"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/sg-bridge@sha256:8dfaa2c6d383c95c85a189ae6af0da426c089a18ffa62ac0acc5f4f8986dbab6?tag=1.5.0-13"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/smart-gateway-rhel8-operator@sha256:c8ba255549fe0b8ff7ce825b22e018938026beb6eda008aa1c3edd551f1d1ea2?tag=5.0.1-4"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/sg-core@sha256:fae8586bc4872450e0f01f99a6202deec63ebd6b2ea8eb5c3f280229fa176da2?tag=5.1.1-3"),
        },
    ]
```
but this on the GitHub runner (no `sg-core`):
```
[2024-06-11T13:32:54Z INFO  spog] [
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/prometheus-webhook-snmp@sha256:fc60b27cb8b8806a71dc0faf7de41be39082d5a9a8c92ca0583e6339471a7513?tag=1.5.2-3"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/service-telemetry-rhel8-operator@sha256:5918c535344b0d0165fe2cd5e4afafbffcf14f09a2759675c765691917fb1459?tag=1.5.1-3"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/sg-bridge@sha256:8dfaa2c6d383c95c85a189ae6af0da426c089a18ffa62ac0acc5f4f8986dbab6?tag=1.5.0-13"),
        },
        Object {
            "purl": String("pkg:oci/registry.redhat.io/stf/smart-gateway-rhel8-operator@sha256:c8ba255549fe0b8ff7ce825b22e018938026beb6eda008aa1c3edd551f1d1ea2?tag=5.0.1-4"),
        },
    ]
```
(see https://github.com/trustification/trustification/actions/runs/9466353119/job/26077901281?pr=1426#step:13:2874)

**Comment by i386x** [comment]
@ctron How guac and storage are exactly synced? It seems to me that we are lacking some synchronization mechanism between containers/micro-services (see log snippets above). It works on my slow T14s but on a blazingly fast GitHub worker machine I get different results every time I rerun the test.

**Comment by i386x** [comment]
I did a bit of refactoring, sorry for a lengthy PR.

**Review by ctron — APPROVED** [review]
That looks great! Especially paying attention to all the details!

I am not sure disabling the debug info is a good idea. I made my peace with cargo eating up my disk space and clean it out every now and then. But I'll leave that to you.

**Comment by i386x** [comment]
> That looks great! Especially paying attention to all the details!

Thanks for the review! :+1: 

> I am not sure disabling the debug info is a good idea. I made my peace with cargo eating up my disk space and clean it out every now and then. But I'll leave that to you.

In case of need this can be overriden via `--config` on the `cargo` side (overriding via environment variable is not supported due to present asterisk (`*`) character). On my side, disabling debug info just for dependencies (the final product still uses debug info) speeds up compilation time from 40 to 11 minutes (I am compiling with `--jobs 1` to prevent memory consumption issues; on GitHub runner which uses multiple cores I see the speed up from 1m to 35s).

**Pull request merged**
