### PR TITLE
[stable] setting strategy (#1032)

### PR DESCRIPTION
**Pull request by desmax74**
Cherry pick of

-  https://github.com/trustification/trustification/pull/1032
- https://github.com/trustification/trustification/pull/1037

### CODE REVIEW

**Comment by ctron** [comment]
I think we should also do this for the indexer pods, and for v11y.

**Comment by desmax74** [comment]
> I think we should also do this for the indexer pods, and for v11y.
@ctron v11y is the only deployment already containing recreate as a strategy

**Comment by desmax74** [comment]
@ctron updated

**Review by ctron — APPROVED** [review]

**Pull request merged**
