### PR TITLE
spog API: Add endpoints discovery

### PR DESCRIPTION
**Pull request by i386x**
Enhance Spog API about endpoints discovery feature. With this feature it is now possible to ask Spog about its vexination, bombastic, and OIDC issuer endpoints it is using.

Example:
```shell
$ curl -s -X GET "http://localhost:8083/.well-known/trustification/endpoints" | jq
{
  "vexination": "http://localhost:8081/",
  "bombastic": "http://localhost:8082/"
}
```

Resolves: #448

Sign-off-by: Jiří Kučera <jkucera@redhat.com>

TODO:
- [x] add tests
- [x] add endpoint to the index
- [x] investigate why OIDC issuer is not included in the response

### CODE REVIEW

**Comment by i386x** [comment]
Seems OIDC issuer is missing despite the fact that keycloak service is running. Investigating.

**Review by ctron — CHANGES_REQUESTED** [review]
I am not sure adding a single issuer makes sense. I am not a fan of adding this to the trait, because it's not really needed.

Currently we already have multiple issuers for the system. And we wouldn't want to expose any internal issuer to the outside through this endpoint. So I guess it's best to just not add it.

**Comment by i386x** [comment]
@ctron ok so just reporting only `vexination` and `bombastic` endpoints is enough? @lulf what do you think?

**Comment by lulf** [comment]
@i386x Sounds good to me. Probably should add v11y and exhort services there as well, now that they've been added.

**Comment by lulf** [comment]
@i386x Thats probably good for now then, I think exhort is somewhat independent of the rest.

**Comment by lulf** [comment]
@i386x I think v11y and collectorist should be all

**Comment by i386x** [comment]
@ctron Are you ok with changes?

**Review by ctron — APPROVED** [review]

**Pull request merged**
