### PR TITLE
feat: allow using custom trust anchors

### PR DESCRIPTION
**Pull request by ctron**
supersedes https://github.com/trustification/trustification/pull/1227

### CODE REVIEW

**Comment by carlosthe19916** [comment]
Tested in CRC and we don't have the error connecting the pods to the Keycloak URL.

I've found an issue though. After everything is correctly deployed, I launched the UI and it never get loaded (see the video below). The reason was that the `.well-known/openid-configuration` endpoint of Keycloak is also using non trusted certificates and somehow the user needs to load it in the browser and accept the risk. If this is considered as an issue I believe we can fix it in a separate PR.

[Screencast from 2024-04-11 13-53-34.webm](https://github.com/trustification/trustification/assets/2582866/b1e9ea45-91da-4e9d-b51f-bec57634e973)

**Review by carlosthe19916 — APPROVED** [review]

**Comment by carlosthe19916** [comment]
Ups. Hold one give me some more minutes for an additional check please

**Comment by ctron** [comment]
> If this is considered as an issue I believe we can fix it in a separate PR.

I don't think this is something that we can fix. This is being triggered by the browser of the user, which we don't have control over. You will either need to add the CRC certificate as a trust anchor to your system (which I would not recommend to do). Or manually add exceptions in the browser for every endpoint.

**Comment by ctron** [comment]
> Ups. Hold one give me some more minutes for an additional check please

I reset your +1, when you're done you can vote again.

**Comment by carlosthe19916** [comment]
> > If this is considered as an issue I believe we can fix it in a separate PR.
> 
> I don't think this is something that we can fix. This is being triggered by the browser of the user, which we don't have control over. You will either need to add the CRC certificate as a trust anchor to your system (which I would not recommend to do). Or manually add exceptions in the browser for every endpoint.

@ctron I agree with you, in regards of the browser there is not much we can do to avoid the issue. However, I made a deeper test and since we have multiple external urls, all of them must be configured with the browser in order to accept the self signed certificate. These are the URLs that need manual "certificate acceptance":
- UI: This is the obvious URl the url will naturally jump and accept the certificate.
- Keycloak: This one is not obvious and users will need to configure the browser
- SpogAPI + Bombastic API + Vexination API. These are also not obvious, and without this the UI will give a false impression of "working". Please watch my video below (sorry a bit long video).

We might need to add some docs stating that it will be the user's responsibility to configure his browser to accept the certificate and make sure all the URLs stated above are configured appropriately. What do you think? This was not defined in the requirement but not sure what we can do about it.

[Screencast from 2024-04-11 14-57-18.webm](https://github.com/trustification/trustification/assets/2582866/94fa3ad8-566f-4eb8-8d0c-e8a383276a38)

**Review by carlosthe19916 — APPROVED** [review]
I'll approve the PR as it works as expected from my side. The issue reported above with the browser is a limitation and we need to coordinate with the docs team to define how to document this.

**Comment by ctron** [comment]
I'll think the note for the docs should be: the browser needs to be configured as well to accept the custom trust anchor.

**Pull request merged**
