### PR TITLE
[TC-1213] - Make the UI to use /api/v1/config

### PR DESCRIPTION
**Pull request by carlosthe19916**
https://issues.redhat.com/browse/TC-1213

## /api/v1/config/public

Screenshot from 2024-04-17 15-44-57

## /api/v1/config

Screenshot from 2024-04-17 15-45-21

### CODE REVIEW

**Comment by carlosthe19916** [comment]
The decision of the UI using the private or public configuration is based on the presence of an access token

**Comment by ctron** [comment]
Cool idea. I guess it should work.

**Comment by carlosthe19916** [comment]
> Cool idea. I guess it should work.

Unfortunately also this didn't work. The UI keep taking the "public" configuration and not the "private" configuration after the authentication is done. So neither this PR nor https://github.com/trustification/trustification/pull/1285 solved the issue.

I tested the solutions creating a container and then deploying it to a OCP where RHTPA was deployed using the Helm charts

```
podman build . -f container_files/Containerfile.services -t quay.io/cferiavi/trustification:MY_TAG
```

**Comment by carlosthe19916** [comment]
@ctron I have found the real issue: we were using nested Contexts (`<Configuration />` ) and both were injecting the same Object type to their children (a `Configuration` object). So every time we used `use_config()` the hook was always trying to get the higher Context. The solution was to avoid having nested Contexts serving the same Object type; we can have nested Contexts but each Context should serve different Object types to avoid collision.

These are the things that this PR is doing:
- There are 2 Contexts each one of them is serving a different type. One is serving a `Configuration` object and the other a `pub struct PrivateConfiguration(pub Configuration);` object. I wrapped the Configuration object in a struct to both Context serve different types
- Instead of just using `use_config()` hook. We now have 2 hooks `use_config_public()` and `use_config_private()`. To make the code verbose and readable (I accept objections on this though)
- In the past there was only one `<Configuration/>` component that initialize the Contexts. Now we have 2 Contexts: `<PublicConfigurationComponent/>` and `<PrivateConfigurationComponent/>`. I added the "Component" suffix to make it easier to differentiate them from the actual Structs with the same name.

Tested in OCP and it worked. Let me know what you think about these changes

**Review by ctron — APPROVED** [review]
I guess it would be possible to use parametrized types. But this is more explicit and the result is the same.

**Pull request merged**
