### PR TITLE
feat: Send organization_id to segment.io

### PR DESCRIPTION
**Pull request by carlosthe19916**
The organization id is a claim coming in the form:
```
"organization": {
    "id": "123456"
},
```

It needs to be sent to segment.io for better tracking of data

### CODE REVIEW

**Comment by carlosthe19916** [comment]
@ctron I removed all personal data being sent to segment. As I recall, Heiko mentioned not to send names and usernames (feel free to correct my memory though). So now we are sending only the "locale" and "organization_id". 

It means that on upstream, we won't send any data and all tracking will be on `Anonymous` mode.
Only on Downstream we will send "organization_id"

**Comment by ctron** [comment]
> It means that on upstream, we won't send any data and all tracking will be on Anonymous mode.
Only on Downstream we will send "organization_id"

What about hashing the e-mail?

**Review by ctron — APPROVED** [review]
Hashing or not, it's good to be merged.

**Comment by carlosthe19916** [comment]
> > It means that on upstream, we won't send any data and all tracking will be on Anonymous mode.
> > Only on Downstream we will send "organization_id"
> 
> What about hashing the e-mail?

Hashing the email might not bring value, as it won't help to identify the user anyway. The primary way of identifying a user as of now is using the `sub` claim and it should serve as way of replacing the HASH-EMAIL.

I'll merge this PR as it would be good to have some feedback from Heiko in the upcoming days.

https://github.com/trustification/trustification/blob/6f7c5481a90e4ac83747fb5180a49cc621386f0c/spog/ui/crates/utils/src/analytics/mod.rs#L210

**Pull request merged**
