### PR TITLE
UI - continuously fetch sboms so they eventually appear after they are uploaded

### PR DESCRIPTION
**Pull request by carlosthe19916**

### CODE REVIEW

**Comment by carlosthe19916** [comment]
@ctron This PR allows pulling data on the tab "products and containers" every 5 seconds to allow uploaded sboms to appear in the table list once they are ready.

I've been thinking about this use case. Unless we are able to make the 2 following endpoints to return the uploaded sbom immediately after they are uploaded then we will always need to continuously pull data in the UI. My point is, as long as there is a delay time (seconds or minutes) between uploading a file and indexing it, then the PULL approach is a must and not an option neither a workaround.

- /api/v1/sbom/search GET (Search on table)
- /api/v1/sbom?id=SBOM_ID GET (Get entity with details)

- Puling data continuously is a common UI practice and it does not represent a risk of killing the backend's resources unless we prove otherwise
- As long as we have the current architecture where the file is uploaded => file send to s3 => file is indexed, then we will always have a delay time (this applies regardless of whether we have a DB or nor). Even if we replace the index with a DB, I don't see how it would make things different.

What are your thoughts on this? If you have something in mind to tackle this issue from a different angle, could you please share it with me? It might be missing something

**Comment by ctron** [comment]
I agree that this is a valid workaround. I am not sure if it will introduce more problems than it will solve. Not because of a bad implementation, but because it things we didn't consider.

I would argue that this approach of workarounds lead to the current state of things.

I think it makes sense to keep this PR in our "bag of tricks", that we can pull it out when absolutely necessary. But let's try to avoid this for now.

One reason for this is: the index sync is currently one minute. Depending on the size of the index, that may be way to short. So we would need to increase it. And while it might technically be possible to poll for 5 or 10 minutes, a user wouldn't wait that long anyway.

**Comment by carlosthe19916** [comment]
Changing the status of this PR to Draft as some suggestions to be implemented came from @PhilipCattanach 
- After uploading an sbom the UI should show an Alert letting the user know that his file has been successfully uploaded
- The default Tab on the Search page should be "Products and containers" as it is the natural way of looking at information. So the order of tabs will be: "Products and containers | packages | CVEs | Advisories"
- The visualization of the CRDA report for each sbom should be done in the "Search main table" and it should be an action within the main table rather than a tab in the "details page".

**Comment by carlosthe19916** [comment]
@ctron Do you mind reviewing this PR please? The following changes were applied after your last review:

- After uploading an sbom the UI should show an Alert letting the user know that his file has been successfully uploaded
- The default Tab on the Search page should be "Products and containers" as it is the natural way of looking at information. So the order of tabs will be: "Products and containers | packages | CVEs | Advisories"
- The visualization of the CRDA report for each sbom should be done in the "Search main table" and it should be an action within the main table rather than a tab in the "details page".

Those were suggestions from @PhilipCattanach 

After this PR is merged I will start looking at https://issues.redhat.com/browse/TC-906

**Comment by carlosthe19916** [comment]
And this is how it should look like:

[Screencast from 2024-01-22 09-57-14.webm](https://github.com/trustification/trustification/assets/2582866/69c60fea-9ea8-4d94-892b-2b3887bb718a)

**Review by ctron — APPROVED** [review]
I am not sure about the dialog. I would prefer the tab. That's my personal preference I guess :D

Anyway, great PR!

**Pull request merged**
