### PR TITLE
Add Privacy Statement for SBOM analysis

### PR DESCRIPTION
**Pull request by carlosthe19916**
https://issues.redhat.com/browse/TC-953

Screenshot from 2024-03-01 14-34-45
Screenshot from 2024-03-01 14-34-38

### CODE REVIEW

**Comment by ctron** [comment]
Wouldn't it make sense to use something like the `Hint` component?

**Comment by carlosthe19916** [comment]
> Wouldn't it make sense to use something like the `Hint` component?

I'm just following the suggested Mockup from UX https://issues.redhat.com/browse/TC-953 xD

Screenshot 2024-02-26 at 11 16 16 AM

**Comment by ctron** [comment]
Ok, in that case :)

**Comment by PhilipCattanach** [comment]
@carlosthe19916 - As I understand it we haven't got the officlal wording , nor have we got the placement in the UI from UXD.  I didn't want you to do anything until both of those were in place.

**Comment by carlosthe19916** [comment]
> @carlosthe19916 - As I understand it we haven't got the officlal wording , nor have we got the placement in the UI from UXD. I didn't want you to do anything until both of those were in place.

Ups, sorry. This PR is a Draft and not a final one. Let's wait for an official confirmation then :)

**Comment by PhilipCattanach** [comment]
Thanks @carlosthe19916 the wording looks fine to me. Please ensure this PR is applied to both the main and release branches.

**Pull request merged**
