### PR TITLE
fix: scope the sidebar so that it has access to the private config

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by carlosthe19916** [comment]
It works locally. But also the current main branch (the one with the bug) works locally. I can not test it unless deployed in a container.

One question. If this block of code is not changed, no matter what the UI will still use the "public" configuration and not the private. ` <Configuration public=true>`. The `use_config` hook takes the configuration from the context set in the parent ` <Configuration public=true>`. I'll create a container manually and see if it works just to be 100% sure

```
 <Configuration public=true>
                    { consent(html!(
                        <BackdropViewer>
                            <ToastViewer>
                                <Segment write_key={backend.endpoints.segment_write_key.clone()}>
                                    <SegmentIdentify />
                                    <OAuth2Configured>
                                        <Console />
                                    </OAuth2Configured>
                                </Segment>
                            </ToastViewer>
                        </BackdropViewer>
                    )) }
                </Configuration>
```

**Comment by carlosthe19916** [comment]
@ctron I created a container based on this PR and shared it with QE to see it working. Unfortunately, although it works locally the bug is still in the container.

**Comment by ctron** [comment]
Hm, if it works locally, then there should be no difference in the contain. That feels more like a container/build issue.

I normally run:

```bash
podman build . -f container_files/Containerfile.services -t quay.io/ctrontesting/trust:latest
```

To build the container. Then:

```bash
podman push quay.io/ctrontesting/trust:latest
```

And then you need to replace the container in the cluster. And ensure that `imagePullPolicy` is set to `Always`.

**Comment by ctron** [comment]
@carlosthe19916 this one can be closed in favor of #1284, right?

**Comment by carlosthe19916** [comment]
> @carlosthe19916 this one can be closed in favor of #1284, right?

Yes, I'll close this PR in favor of #1284

**Pull request closed without merging**
