### PR TITLE
[TC-803] - Package details: set namespace + name as title

### PR DESCRIPTION
**Pull request by carlosthe19916**
Screenshot from 2023-12-07 18-27-48

### CODE REVIEW

**Comment by carlosthe19916** [comment]
@ctron I added a commit and here is how it should look like:
- The namespace and name of the page is in the title. When it is a maven package then `namespace:name` otherwise `namespace/name`
- The version of the packages is below the title
- The qualifiers are on the right of the version

I hope that should be enough for a user to understand which package he is looking at. Could you review this PR please? Not sure when the freeze of Merging PRs will start though

Screenshot from 2023-12-08 11-02-22

**Review by ctron — CHANGES_REQUESTED** [review]
Great improvement! I think we should also add the path (if present), as that can also make a difference.

**Comment by carlosthe19916** [comment]
> Great improvement! I think we should also add the path (if present), as that can also make a difference.

Yeah, I thought about it. But I saw all packages to have empty path on the packages table. At least I could not find any to understand the average length to decide whether or not to put it as a plain text or as a label or any other option. I will go with plain text. Give me a moment I will add another commit

**Comment by carlosthe19916** [comment]
@ctron done! the `path` (if exists) will be located below the version. If the path text is too long it does not matter since it will have its whole row just for it. I didn't add it as a label (like the qualifiers) to avoid long text that might affect the look and feel.

**Review by ctron — APPROVED** [review]

**Pull request merged**
