### PR TITLE
TC-1886 sbom license scanner

### PR DESCRIPTION
**Pull request by bxf12315**

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@bxf12315 - Thank you for raising the PR.
I know @dejanb is flat out with vulnerability correlation work. Can I suggest adding @mrizzi as a reviewer instead as Marco has some context about this work.

**Review by mrizzi — COMMENTED** [review]
Happy to be the reviewer 👍 
@bxf12315 maybe it's worth investing some time in having the tests to run successfully for moving this PR forward.

**Comment by bxf12315** [comment]
> Happy to be the reviewer 👍 @bxf12315 maybe it's worth investing some time in having the tests to run successfully for moving this PR forward.
Here is unit test[1] to prove that it can work. I will try to fix the clippy issues.
[1] https://github.com/trustification/trustification/pull/2040/files#diff-b4a62e0ff7736ca9f3fb4aa5b5a1a46a0efc85d1e78a3c9e86bb106a316f6101R139

**Comment by carlosthe19916** [comment]
@bxf12315 thanks for the last commit. I confirm I can download the file after applying your latest changes.
But the file downloaded is something like: `ec2a36c8-7a80-4217-b91b-5fa8ee2550bc.zip` and it is due to the configuration done in the Header "Content-disposition" which currently sets the SBOM Id rather than the SBOM name. 

Could we set the "Content-disposition" to point to the SBOM name please?
-  I notice the variable name here https://github.com/bxf12315/trustification/blob/license-export/spog/api/src/endpoints/license.rs#L39 says `sbom_name` but that actually is the `sbom_id` not the name of the sbom.

**Comment by mrizzi** [comment]
> @bxf12315 thanks for the last commit. I confirm I can download the file after applying your latest changes. But the file downloaded is something like: `ec2a36c8-7a80-4217-b91b-5fa8ee2550bc.zip` and it is due to the configuration done in the Header "Content-disposition" which currently sets the SBOM Id rather than the SBOM name.
> 
> Could we set the "Content-disposition" to point to the SBOM name please?
> 
> * I notice the variable name here https://github.com/bxf12315/trustification/blob/license-export/spog/api/src/endpoints/license.rs#L39 says `sbom_name` but that actually is the `sbom_id` not the name of the sbom.

It might be even better to have the SBOM name followed by the `_licenses` suffix in order, e.g. `quarkus_licenses.zip`, to make it easier for users to remember what that file is about once it will be downloaded in their computers.

**Comment by bxf12315** [comment]
> @bxf12315 thanks for the last commit. I confirm I can download the file after applying your latest changes. But the file downloaded is something like: `ec2a36c8-7a80-4217-b91b-5fa8ee2550bc.zip` and it is due to the configuration done in the Header "Content-disposition" which currently sets the SBOM Id rather than the SBOM name.
> 
> Could we set the "Content-disposition" to point to the SBOM name please?
> 
> * I notice the variable name here https://github.com/bxf12315/trustification/blob/license-export/spog/api/src/endpoints/license.rs#L39 says `sbom_name` but that actually is the `sbom_id` not the name of the sbom.

Done

**Comment by bxf12315** [comment]
> > @bxf12315 thanks for the last commit. I confirm I can download the file after applying your latest changes. But the file downloaded is something like: `ec2a36c8-7a80-4217-b91b-5fa8ee2550bc.zip` and it is due to the configuration done in the Header "Content-disposition" which currently sets the SBOM Id rather than the SBOM name.
> > Could we set the "Content-disposition" to point to the SBOM name please?
> > 
> > * I notice the variable name here https://github.com/bxf12315/trustification/blob/license-export/spog/api/src/endpoints/license.rs#L39 says `sbom_name` but that actually is the `sbom_id` not the name of the sbom.
> 
> It might be even better to have the SBOM name followed by the `_licenses` suffix in order, e.g. `quarkus_licenses.zip`, to make it easier for users to remember what that file is about once it will be downloaded in their computers.

Done

**Comment by carlosthe19916** [comment]
@bxf12315 thanks. I've tested your PR and it works as I was expecting. Also @mrizzi 's suggestion was applied.

**Comment by carlosthe19916** [comment]
@bxf12315 to me this PR is ready (from the UI point of view). I must say that I just tested the file being downloaded from the backend. I did not test nor validated the content of the zip file being downloaded. I mean, I saw data in the zip file but I didn't test that the content of the CSV files are exactly what we need.

@mrizzi are you happy with the content of the CSV files? Or is this something we can defer to QE? I am asking so we can merge this PR?

**Comment by bxf12315** [comment]
> @bxf12315 to me this PR is ready (from the UI point of view). I must say that I just tested the file being downloaded from the backend. I did not test nor validated the content of the zip file being downloaded. I mean, I saw data in the zip file but I didn't test that the content of the CSV files are exactly what we need.
yes, I also waiting for @PhilipCattanach's feedback. 
> 
> @mrizzi are you happy with the content of the CSV files? Or is this something we can defer to QE? I am asking so we can merge this PR?

**Comment by carlosthe19916** [comment]
@bxf12315 I created a PR to your branch here https://github.com/bxf12315/trustification/pull/7
It should help us to sanitize the sbom names that are used in filenames.

I am also sharing here the SBOM that Pavel from QE shared with us to validate the code works. I tested it with the UI and it worked. Feel free to test my PR and merge it in your branch if you find it useful :)

[trustification-product-1-2-1-sbom.json](https://github.com/user-attachments/files/18076896/trustification-product-1-2-1-sbom.json)

**Review by m-brophy — APPROVED** [review]
lgtm

**Pull request merged**
