### PR TITLE
Git image  

### PR DESCRIPTION
**Pull request by desmax74**
See: https://issues.redhat.com/browse/TC-952

### CODE REVIEW

**Review by ctron — CHANGES_REQUESTED** [review]
I think it makes sense to have a label to direct people to the source of the repo:

Like:  https://github.com/trustification/trustification/blob/d20b84deba42d727cbdcf68cace81be458533f64/container_files/Containerfile.docs#L17

And I guess we need to publish it.

**Review by ctron — COMMENTED** [review]
I am sorry, but I still don't see how this is being published.

**Comment by desmax74** [comment]
@ctron added build and publish on ghcr.io

**Pull request merged**
