### PR TITLE
xtask test: Support code coverage

### PR DESCRIPTION
**Pull request by i386x**
Generate coverage reports for code covered by tests.

Issue: #466

### CODE REVIEW

**Comment by i386x** [comment]
Actual output of units and integs:
```
[jkucera@test1176 trustification]$ SELINUX_VOLUME_OPTIONS=':Z' PATH=$HOME/.cargo/bin/:$PATH cargo xtask test -j 1 -c 1 --ui
    Finished dev [unoptimized + debuginfo] target(s) in 0.59s
     Running `target/debug/xtask test -j 1 -c 1 --ui`
$ npm ci

added 2 packages, and audited 3 packages in 1s

found 0 vulnerabilities
$ trunk-ng build
2024-01-05T18:42:32.562553Z  INFO 🚀 Starting trunk-ng 0.17.12    
2024-01-05T18:42:32.564812Z  INFO 📦 starting build
2024-01-05T18:42:32.565857Z  INFO spawning asset pipelines
2024-01-05T18:42:32.978581Z  INFO spawned hook bash command_arguments=["dev/trunk-hook.sh"]
2024-01-05T18:42:32.978608Z  INFO spawning hook stage=Build command=bash
2024-01-05T18:42:32.978661Z  INFO copying directory path="branding"
2024-01-05T18:42:32.978681Z  INFO copying directory path="assets"
2024-01-05T18:42:32.978741Z  INFO copying file path="assets/codicon.ttf"
2024-01-05T18:42:32.978763Z  INFO copying directory path="node_modules/@patternfly/patternfly/assets"
2024-01-05T18:42:32.978771Z  INFO copying directory path="node_modules/@fortawesome/fontawesome-free/webfonts"
2024-01-05T18:42:32.978814Z  INFO building spog-ui
2024-01-05T18:42:32.979751Z  INFO finished copying file path="assets/codicon.ttf"
2024-01-05T18:42:32.980846Z  INFO compiling sass/scss path="styles/main.scss"
Trunk profile: debug
Copy dev folder to staging: /home/jkucera/development/upstream/trustification/spog/ui/dist/.stage
2024-01-05T18:42:32.981771Z  INFO finished copying directory path="node_modules/@fortawesome/fontawesome-free/webfonts"
2024-01-05T18:42:32.982389Z  INFO finished copying directory path="branding"
2024-01-05T18:42:32.984732Z  INFO finished copying directory path="assets"
Copy branding-default folder to branding
2024-01-05T18:42:32.987073Z  INFO finished hook bash
2024-01-05T18:42:32.991934Z  INFO finished copying directory path="node_modules/@patternfly/patternfly/assets"
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
2024-01-05T18:42:33.335258Z  INFO fetching cargo artifacts
2024-01-05T18:42:33.713640Z  INFO finished compiling sass/scss path="styles/main.scss"
2024-01-05T18:42:35.604397Z  INFO calling wasm-bindgen for spog-ui
2024-01-05T18:42:40.643087Z  INFO rust build complete
2024-01-05T18:42:40.645673Z  INFO applying new distribution
2024-01-05T18:42:40.660936Z  INFO ✅ success
Checking if webdriver is up...
Starting ChromeDriver 119.0.6045.199 (f6fcaed63cb61e2eeff44a3268ac6fbaaa2a8f88-refs/branch-heads/6045@{#1518}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
$ cargo test --jobs 1 -- --test-threads 1
    Finished test [unoptimized + debuginfo] target(s) in 1.22s
     Running unittests src/lib.rs (target.cov/debug/deps/bombastic-5303f1a12482dc1e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/bombastic_api-2013b22eb097ad45)

running 4 tests
test sbom::tests::parse_cyclonedx ... ok
test sbom::tests::parse_cyclonedx_syft ... ok
test sbom::tests::parse_spdx ... ok
test sbom::tests::parse_spdx_syft ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

     Running unittests src/lib.rs (target.cov/debug/deps/bombastic_index-4c48ed42d239747d)

running 17 tests
test packages::tests::test_search_packages_by_name ... ok
test packages::tests::test_search_packages_by_package_type ... ok
test packages::tests::test_search_packages_by_purl ... ok
test packages::tests::test_search_packages_by_supplier ... ok
test packages::tests::test_search_packages_empty_query ... ok
test sbom::tests::test_all ... ok
test sbom::tests::test_explain ... ok
test sbom::tests::test_metadata ... ok
test sbom::tests::test_not ... ok
test sbom::tests::test_purl_qualifiers ... ok
test sbom::tests::test_search_created ... ok
test sbom::tests::test_search_form ... ok
test sbom::tests::test_search_namespace ... ok
test sbom::tests::test_search_package ... ok
test sbom::tests::test_sorting ... ok
test sbom::tests::test_sorting_noterms ... ok
test sbom::tests::test_supplier ... ok

test result: ok. 17 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 93.90s

     Running unittests src/lib.rs (target.cov/debug/deps/bombastic_indexer-e98b3045d645102a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/bombastic_model-d87b15e934a46bb2)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target.cov/debug/deps/bommer-35b14e8998e86f47)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/bommer_api-e252a6b40b454b65)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/collector-17bb0e39b0caee50)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/collector_client-4b07451f2927c0d9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/collector_osv-142c4746be57b82b)

running 7 tests
test client::schema::tests::test_no_serialize_null_fields ... ok
test client::schema::tests::test_package_serialization ... ok
test client::tests::empty_response ... ok
test client::tests::empty_vulns ... ok
test client::tests::no_vulns ... ok
test client::tests::query_vuln ... ok
test client::tests::some_vulns ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.80s

     Running unittests src/lib.rs (target.cov/debug/deps/collector_snyk-b0ea635243a59362)

running 4 tests
test client::test::single ... ignored, because following variables not found:
SNYK_ORG_ID, SNYK_TOKEN

test rewrite::test::no_rewrite ... ok
test rewrite::test::rewrite_redhat_no_el_version ... ok
test rewrite::test::rewrite_redhat_with_el_version ... ok

test result: ok. 3 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests src/lib.rs (target.cov/debug/deps/collectorist-4daaf0c0d32914d2)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/collectorist_api-ff7248f5dc76c56d)

running 5 tests
test db::test::filter_purls_for_scan ... ok
test db::test::insert_purl ... ok
test db::test::update_purl_scan_time ... ok
test server::collector::test::collector_config_round_trip ... ok
test server::collector::test::get_collector_config ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.11s

     Running unittests src/lib.rs (target.cov/debug/deps/collectorist_client-c3aa5e5e0bbbeef2)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/exhort-4d9b514ad0f391dc)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/exhort_api-29b9103ede0d8a8a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/exhort_model-8ff6faa6962d1150)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/exporter-d9b5b0a49d3eaf80)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target.cov/debug/deps/reservoir-c9ff26ee393072b0)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/reservoir_api-decaa3c2a520d959)

running 1 test
test pattern::cpe::test::construct_simple ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/spog-09ffe5d9d7411e25)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/spog_api-c5c5b527b896f176)

running 5 tests
test config::test::parse_default ... ok
test endpoints::sbom::vuln::analyze::test::test_scrape_remediations ... ok
test service::guac::test::test_find_vulnerability ... ignored
test service::guac::test::test_product_by_cve ... ignored
test service::guac::test::test_product_by_package ... ignored

test result: ok. 2 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.07s

     Running unittests src/bin/gen_openapi.rs (target.cov/debug/deps/gen_openapi-b87d7c17df6471af)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/spog_model-0d264eb5b2d5c741)

running 3 tests
test config::test::test_deserialize_options_1 ... ok
test config::test::test_deserialize_options_2 ... ok
test config::test::test_ensure_eq ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target.cov/debug/deps/trust-bc0d7104dd74acb8)

running 1 test
test tests::verify_cli ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_analytics-0ec7fa6d25053cd6)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_auth-277b10852fd10bd2)

running 3 tests
test authenticator::test::test_no_scope_mapping ... ok
test authenticator::test::test_scope_mapping ... ok
test client::test::test_expires_before ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_common-585fa7ea46ff3bc1)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_event_bus-09bd68f79726dcce)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_index-48222120262c2c41)

running 6 tests
test tests::test_basic_index ... ok
test tests::test_directory_sync_failure ... ok
test tests::test_duplicates ... ok
test tests::test_index_dir_reset ... ok
test tests::test_index_removal ... ok
test tests::test_zero_limit ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.12s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_indexer-39a00c894a6a3437)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_infrastructure-75af396d569d6616)

running 1 test
test app::http::test::default_config_converts ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_storage-46c0f54a22758cfe)

running 13 tests
test tests::test_minio_decode ... ok
test tests::test_s3_decode ... ok
test tests::test_s3_path_keys ... ok
test validator::tests::none ... ok
test validator::tests::sbom_bzip2_invalid ... ok
test validator::tests::sbom_bzip2_invalid_license ... ok
test validator::tests::sbom_bzip2_valid ... ok
test validator::tests::sbom_json_invalid ... ok
test validator::tests::sbom_json_valid ... ok
test validator::tests::sbom_zstd_invalid ... ok
test validator::tests::sbom_zstd_valid ... ok
test validator::tests::vex_json_invalid ... ok
test validator::tests::vex_json_valid ... ok

test result: ok. 13 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.94s

     Running unittests src/lib.rs (target.cov/debug/deps/trustification_version-75c2d06df188ca1c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y-509527cb746784d7)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y_api-460742a953e81833)

running 6 tests
test db::test::ingest_maximal ... ok
test db::test::ingest_minimal ... ok
test db::test::ingest_updated_overwrite ... ok
test server::vulnerability::test::get_none ... ignored, No substitute for Storage
test server::vulnerability::test::get_one ... ignored, No substitute for Storage
test server::vulnerability::test::get_several ... ignored, No substitute for Storage

test result: ok. 3 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.03s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y_client-f53d236bc065f381)

running 1 test
test test::serialization ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y_index-5ad3eaa8573fca53)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y_indexer-eb061362993fead2)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y_model-506bf615ca0f21fe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/v11y_walker-a024e2ba0a82b1ca)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/vexination-b6fbc3f7bc1fddac)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/vexination_api-ff994ae3248f1c49)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/vexination_index-db9977e02f4695bd)

running 24 tests
test tests::test_all ... ok
test tests::test_delete_document ... ok
test tests::test_free_form_dates ... ok
test tests::test_free_form_predicate_critical ... ok
test tests::test_free_form_predicate_final ... ok
test tests::test_free_form_predicate_high ... ok
test tests::test_free_form_primary_scoped ... ok
test tests::test_free_form_ranges ... ok
test tests::test_free_form_simple_primary ... ok
test tests::test_free_form_simple_primary_2 ... ok
test tests::test_free_form_simple_primary_3 ... ok
test tests::test_metadata ... ok
test tests::test_ngrams ... ok
test tests::test_ngrams_nocase ... ok
test tests::test_ngrams_scope ... ok
test tests::test_packages ... ok
test tests::test_products ... ok
test tests::test_products_by_not_affected ... ok
test tests::test_products_partial ... ok
test tests::test_query_and_products ... ok
test tests::test_severity ... ok
test tests::test_severity_count ... ok
test tests::test_sorting ... ok
test tests::test_sorting_noterms ... ok

test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 22.35s

     Running unittests src/lib.rs (target.cov/debug/deps/vexination_indexer-28e17cd3552dd4b7)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/vexination_model-560f69164fdaafa9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target.cov/debug/deps/vexination_walker-2535fe7a39411074)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bombastic

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bombastic-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bombastic-index

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bombastic-indexer

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bombastic-model

running 3 tests
test src/packages/mod.rs - packages::PackageInfo::Type (line 12) ... ignored
test src/search.rs - search::Packages::Package (line 15) ... ignored
test src/search.rs - search::Packages::Type (line 25) ... ignored

test result: ok. 0 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bommer-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collector

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collector-client

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collector-osv

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collector-snyk

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collectorist

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collectorist-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests collectorist-client

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests exhort

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests exhort-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests exhort-model

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests exporter

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests reservoir-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests spog

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests spog-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests spog-model

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-analytics

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-auth

running 1 test
test src/authenticator/user.rs - authenticator::user::UserDetails (line 14) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 10.95s

   Doc-tests trustification-common

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-event-bus

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-index

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-indexer

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-infrastructure

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-storage

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests trustification-version

running 4 tests
test src/lib.rs - (line 19) ... ignored
test src/lib.rs - (line 33) ... ignored
test src/lib.rs - (line 7) ... ignored
test src/version.rs - version::configurator (line 35) ... ignored

test result: ok. 0 passed; 0 failed; 4 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y-client

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y-index

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y-indexer

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y-model

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests v11y-walker

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests vexination

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests vexination-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests vexination-index

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests vexination-indexer

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests vexination-model

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests vexination-walker

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

$ cargo test -p integration-tests --jobs 1 --features ui -- --test-threads 1
    Finished test [unoptimized + debuginfo] target(s) in 0.47s
     Running unittests src/lib.rs (target.cov/debug/deps/integration_tests-11a24bb1bc0780a6)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/bombastic.rs (target.cov/debug/deps/bombastic-064d4ec0666a6211)

running 24 tests
test bombastic_bad_search_queries ... ok
test bombastic_deletion ... ok
test bombastic_package_search ... ok
test bombastic_reindexing ... ok
test bombastic_sbom_search ... ok
test delete_happy_sbom ... ok
test delete_missing_sbom ... ok
test get_sbom_with_invalid_id ... ok
test get_sbom_with_missing_id ... ok
test invalid_bzip2_encoded ... [2024-01-05T18:46:13Z ERROR bombastic_model::data] error=Error parsing SBOM (CycloneDX: Failed to deserialize JSON: missing field `bomFormat` at line 155095 column 1, SPDX: error parsing the expression: Parsing for expression `Parsing for expression `GPLV2 AND REDISTRIBUTABLE,-NO-MODIFICATION-PERMITTED` failed.` failed. at line 4975 column 79)
[2024-01-05T18:46:13Z ERROR trustification_storage::validator] Invalid SBOM: Error parsing SBOM (CycloneDX: Failed to deserialize JSON: missing field `bomFormat` at line 155095 column 1, SPDX: error parsing the expression: Parsing for expression `Parsing for expression `GPLV2 AND REDISTRIBUTABLE,-NO-MODIFICATION-PERMITTED` failed.` failed. at line 4975 column 79)
ok
test reject_no_auth_upload ... ok
test reject_non_manager_upload ... ok
test sbom_delete_unauthorized ... ok
test sbom_delete_user_not_allowed ... ok
test sbom_invalid_encoding ... ok
test sbom_invalid_type ... ok
test sbom_upload_empty_file ... ok
test sbom_upload_empty_json ... [2024-01-05T18:46:38Z ERROR bombastic_model::data] error=Error parsing SBOM (CycloneDX: Failed to deserialize JSON: missing field `bomFormat` at line 1 column 2, SPDX: missing field `spdxVersion` at line 1 column 2)
[2024-01-05T18:46:38Z ERROR trustification_storage::validator] Invalid SBOM: Error parsing SBOM (CycloneDX: Failed to deserialize JSON: missing field `bomFormat` at line 1 column 2, SPDX: missing field `spdxVersion` at line 1 column 2)
ok
test sbom_upload_unauthorized ... ok
test sbom_upload_user_not_allowed ... ok
test upload_happy_sbom ... ok
test upload_sbom_existing_with_change ... ok
test upload_sbom_existing_without_change ... ok
test valid_bzip2_encoded ... ok

test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 121.13s

     Running tests/spog.rs (target.cov/debug/deps/spog-6891b2d970b40b27)

running 7 tests
test spog_crda_integration ... ignored, because variable CRDA_URL not found
test spog_dependencies ... ignored
test spog_endpoints ... [2024-01-05T18:47:03Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
ok
test spog_search_correlation ... [2024-01-05T18:47:06Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
ok
test spog_search_forward_bombastic ... [2024-01-05T18:47:23Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
[2024-01-05T18:47:23Z ERROR spog_api::app_state] error=response error: 400 Bad Request / index error: error parsing query Parser error: found end of input at 7..8
[2024-01-05T18:47:23Z ERROR spog_api::endpoints::sbom::search] error=response error: 400 Bad Request / index error: error parsing query Parser error: found end of input at 7..8
ok
test spog_search_forward_vexination ... [2024-01-05T18:47:26Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
ok
test spog_version ... [2024-01-05T18:47:29Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
ok

test result: ok. 5 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 30.30s

     Running tests/ui.rs (target.cov/debug/deps/ui-00863cd905e600b0)

running 3 tests
test ensure_default_values ... [2024-01-05T18:47:33Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
FAILED
test ensure_page_state ... [2024-01-05T18:47:57Z ERROR spog_api::app_state] error=response error: 404 Not Found / storage error: object not found
FAILED
test issue_tc_587 ... ignored, because variable CRDA_URL not found

failures:

---- ensure_default_values stdout ----
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
UI check: 200 OK
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: an element could not be located on the page using the given search parameters: no such element: element(s) not found using selectors: [CSS(.pf-v5-c-button.pf-m-primary)]', integration-tests/src/ui.rs:111:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'ensure_default_values' panicked at 'explicit panic', integration-tests/tests/ui.rs:121:1

---- ensure_page_state stdout ----
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
Error initializing logging: SetLoggerError(())
UI check: 200 OK
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: an element could not be located on the page using the given search parameters: no such element: element(s) not found using selectors: [CSS(.pf-v5-c-button.pf-m-primary)]', integration-tests/src/ui.rs:111:43
thread 'ensure_page_state' panicked at 'explicit panic', integration-tests/tests/ui.rs:141:1


failures:
    ensure_default_values
    ensure_page_state

test result: FAILED. 0 passed; 2 failed; 1 ignored; 0 measured; 0 filtered out; finished in 47.83s

error: test failed, to rerun pass `-p integration-tests --test ui`
Error: command exited with non-zero code `cargo test -p integration-tests --jobs 1 --features ui -- --test-threads 1`: 101
[jkucera@test1176 trustification]$
```
Integs are failing with some errors. Also I noticed that when running UI tests Chromium web driver pop ups several windows that must be closed manually after the tests are finished.

**Comment by helio-frota** [comment]
> Also I noticed that when running UI tests Chromium web driver pop ups several windows that must be closed manually after the tests are finished

@i386x not sure but I think it should work with `headless` argument.

`--headless` or  `--headless=new` depending on the chromedriver version.

**Review by bobmcwhirter — CHANGES_REQUESTED** [review]
LGTM, I just request an addition to a README on how to execute this locally.  `cargo xtask $what` or whatever, and then how to use the results.

**Comment by i386x** [comment]
> LGTM, I just request an addition to a README on how to execute this locally. `cargo xtask $what` or whatever, and then how to use the results.

Done. Add some info to `DEVELOPING.md`.

**Pull request merged**
