### PR TITLE
Single developing

### PR DESCRIPTION
**Pull request by lulf**
requires #56

### CODE REVIEW

**Review by dejanb — APPROVED** [review]
Looks good and works on my machine.

I pushed just one commit with some small improvements. Give it a look and let me know if they are OK

We can maybe provide some util script that would start services (with the option to exclude or more that are being worked on). But we can do that in a separate PR

**Comment by lulf** [comment]
Looks good, thanks!

**Comment by lulf** [comment]
I'm creating a compose file now that can be used to run it all, maybe it would be helpful if one wants to just run all services. Then if you develop a specific one, you can comment that out from the compose file for instance?

**Comment by dejanb** [comment]
> I'm creating a compose file now that can be used to run it all, maybe it would be helpful if one wants to just run all services. Then if you develop a specific one, you can comment that out from the compose file for instance?

Yeah, that sounds like a much better solution :)

**Pull request merged**
